services:
  mysql:
    image: mysql:8.0
    container_name: mysql-todo-app
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_DATABASE: todoapp
      MYSQL_USER: user
      MYSQL_PASSWORD: 12345
    ports:
      - "3307:3306"

  todo-app:
    image: todo-app:latest
    container_name: todo-app
    ports:
      - "8080:8080"

  todo-app-fe:
    image : todo-app-fe:latest
    container_name:
      ports:
        - "5432:5432"