// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('Create Task', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('Create Task', async function() {
    await driver.get("http://localhost:5173/")
    await driver.manage().window().setRect({ width: 1552, height: 849 })
    await driver.findElement(By.css("div:nth-child(1) > .p-2")).click()
    await driver.findElement(By.css("div:nth-child(1) > .p-2")).sendKeys("Do homework Now")
    await driver.findElement(By.css(".h-24")).click()
    await driver.findElement(By.css(".h-24")).sendKeys("This is essential")
    await driver.findElement(By.css(".bg-blue-600")).click()
    await driver.findElement(By.css(".swal2-confirm")).click()
  })
})
