// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('Delete test', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('Delete test', async function() {
    await driver.get("http://localhost:5173/")
    await driver.manage().window().setRect({ width: 1552, height: 849 })
    await driver.findElement(By.css(".bg-gray-300:nth-child(1) > .border")).click()
    await driver.findElement(By.css(".swal2-confirm")).click()
    await driver.findElement(By.css(".swal2-confirm")).click()
  })
})
